name: Feature Request
description: Suggest an idea for Heroes Launcher
labels: "enhancement :sparkles:"
body:
- type: textarea
  attributes:
    label: Problem Description
    description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
  validations:
    required: false
- type: textarea
  attributes:
    label: Proposed Solution
    description: Describe the solution you'd like in a clear and concise manner.
  validations:
    required: false
- type: textarea
  attributes:
    label: New Feature or Change to Existing Feature
    description: If suggesting a new feature or change to an existing feature, describe it in detail.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context here.
  validations:
    required: false
